#ifndef TEXTURE_H
#define TEXTURE_H
#include <gctypes.h>
enum TextureFormat {
TEX_FMT_RGBA16,
TEX_FMT_RGBA32,
TEX_FMT_I8,
TEX_FMT_IA4,
};
extern void LoadTextureFromFile(const char*filename,TextureFormat type,int slot,int alpha=-1,bool linear=false);
// Used for loading textures that have been converted using bin2o
// id is the ID generated by bin2o
extern void LoadTextureFromMemory(s32 id,void*data,u32 size,int slot);
extern void LoadPNGFromMemory(const uint8_t*pngdata,u32 size,TextureFormat type, int slot,int alpha=-1,bool linear=false);
#endif//EXTURE_H
